language: node_js
node_js:
  - "stable"
services:
  - xvfb
addons:
    firefox: latest
    chrome: stable
install:
  - npm install
  - npm run build
script:
  - npm test
  - cat coverage/firefox/lcov.info | node_modules/.bin/coveralls